### ISSUE TITLE
Numba interfering with the installation of mpi4py

### ISSUE THREAD

**Issue by RemiLehe** [conda-forge/mpi4py-feedstock#1]
Hi, 

I have been using the `conda-forge` channel for `mpi4py` for a while: thanks a lot for providing it!

However, recently I observed that installing `numba` (http://numba.pydata.org/) interferes with the installation of `mpi4py`. More precisely, I did a few tests on Travis CI, so as to be able to share them: compare for instance

- [this commit](https://github.com/RemiLehe/test_gcc_conda/commit/0424577d4888ed39f31836c20877518c8d2eaa1f) which [fails](https://travis-ci.org/RemiLehe/test_gcc_conda/builds/167505762) on Travis CI due to the installation of numba
- [this commit](https://github.com/RemiLehe/test_gcc_conda/commit/7672316877b85b3a29a4fde1b4d5e147604e3c51) which [succeeds](https://travis-ci.org/RemiLehe/test_gcc_conda/builds/167506377) on Travis CI, since numba was removed

Interestingly, although the error is due to `gcc`, installing only `gcc` instead of `mpi4py` does not result in an error: https://travis-ci.org/RemiLehe/test_gcc_conda/builds/167504447

Any idea what is happening here?

Thanks a lot for your help!

**Comment by ocefpaf** [comment]
@RemiLehe I believe the problem is unrelated to `mpi4py` or `numba`. It seems to be an old bug in `defaults` `gcc` that re-surfaced. I lost the thread about this issue but I believe is was already solved. Can you try to kick your CIs again and see if that is gone?

**Comment by RemiLehe** [comment]
Yes, you're right, this is now fixed!
Sorry to bother you with this issue, and thanks for your help!

**Comment by ocefpaf** [comment]
No problem.
