### ISSUE TITLE
using openmpi?

### ISSUE THREAD

**Issue by cehbrecht** [conda-forge/mpi4py-feedstock#11]
The current conda package for `mpi4py` has a dependency to `mpich`. But it is possible to use `mpi4py` also with `openmpi` but then one needs to install `mpi4py` manually. 

Could `mpich` and `openmpi` be used as optional dependencies?

**Comment by cehbrecht** [comment]
oops ... seems to be there is already a PR for this #10.

**Comment by minrk** [comment]
closed by #10
