### ISSUE TITLE
Specifying MPI variants from `conda` command line

### ISSUE THREAD

**Issue by RemiLehe** [conda-forge/mpi4py-feedstock#12]
Hi, 

I see that the `mpi4py` conda package now has MPI variants (mpich/openmpi), which is great!
I was wondering how to specify the desired variant on the `conda install` command line.

Thanks!

**Comment by minrk** [comment]
You can ask for the mpi provider and mpi together:

    conda install mpich mpi4py

or specify the build string for mpi4py:

    conda install mpi4py=*=*mpich*

mpi variants haven't propagated to too many packages, to there's a good chance you might end up forced back onto mpich if you need to use any other packages that don't yet have builds for both variants.

**Comment by RemiLehe** [comment]
Thanks for the prompt answer!
It seems that, for OSX, the variants have only been built for python2.7. Would it be possible to have them for python3 as well?

**Comment by dalcinl** [comment]
@minrk I think something went wrong, the packages do not have the `pyXY` tag in the build string: https://anaconda.org/conda-forge/mpi4py/files

**Comment by minrk** [comment]
@dalcinl oops! Should be fixed by #13

**Comment by RemiLehe** [comment]
I just realized this now works fine fore me on OSX. Thanks a lot for PR #13 !
Should I close the issue?

**Comment by minrk** [comment]
Yes, I should have closed it automatically. Thanks!
