### ISSUE TITLE
mpi4py crashes at runtime, on MacOS

### ISSUE THREAD

**Issue by RemiLehe** [conda-forge/mpi4py-feedstock#23]
Issue: 
After installing mpi4py on MacOSX (`conda install -c conda-forge mpi4py`), running the following line
```
mpirun -np 1 python -c "from mpi4py import MPI"
```
results in the following error:
```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/rlehe/miniconda3/envs/mpi4py/lib/libopen-pal.40.dylib
  Expected in: flat namespace

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/rlehe/miniconda3/envs/mpi4py/lib/libopen-pal.40.dylib
  Expected in: flat namespace

Trace/BPT trap: 5
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/rlehe/miniconda3/envs/mpi4py:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h01d97ff_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
libcxx                    8.0.1                         0    conda-forge
libcxxabi                 8.0.1                         0    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               4.0.0                         2    conda-forge
llvm-openmp               8.0.1                h770b8ee_0    conda-forge
mpi                       1.0                     openmpi    conda-forge
mpi4py                    3.0.2            py37h5017f14_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
openmpi                   4.0.1                hfcebdee_2    conda-forge
openssl                   1.1.1c               h01d97ff_0    conda-forge
pip                       19.2.2                   py37_0    conda-forge
python                    3.7.3                h93065d6_1    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sqlite                    3.29.0               hb7d70f7_0    conda-forge
tk                        8.6.9             h2573ce8_1002    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h01d97ff_1005    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : mpi4py
    active env location : /Users/rlehe/miniconda3/envs/mpi4py
            shell level : 2
       user config file : /Users/rlehe/.condarc
 populated config files : /Users/rlehe/.condarc
          conda version : 4.7.11
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /Users/rlehe/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/rlehe/miniconda3/pkgs
                          /Users/rlehe/.conda/pkgs
       envs directories : /Users/rlehe/miniconda3/envs
                          /Users/rlehe/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.3 Darwin/15.4.0 OSX/10.11.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

**Comment by dalcinl** [comment]
The builds are done in Azure Pipelines using a macOS 10.13 image (High Sierra).
The function `clock_gettime()` was added in macOS 10.12 (Sierra).
According to your log, you are running macOS 10.11 (El Capitan).

**Comment by RemiLehe** [comment]
OK, thanks for clarifying.
Should I just close the issue then? (I think it makes sense that `conda-forge` only supports the latest MacOS.)

**Comment by dalcinl** [comment]
> I think it makes sense that `conda-forge` only supports the latest MacOS.

Well, the latest is actually macOS 10.14 (Mojave). The oldest available in Azure Pipelines is macOS 10.13, so that's what `conda-forge` uses.

**Comment by ax3l** [comment]
Update from gitter: technically, macOS 10.9+ (Mavericks) is supported by conda-forge and only some packages such as `openmpi` and `qt` require 10.12+ (Sierra).
-- @isuruf (paraphrased)

https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks

**Comment by ax3l** [comment]
macOS 10.9+ support will be re-enabled when rebuilding against OpenMPI 4.0.2: https://github.com/conda-forge/openmpi-feedstock/pull/46

**Comment by barracuda156** [comment]
> OK, thanks for clarifying.
> Should I just close the issue then? (I think it makes sense that `conda-forge` only supports the latest MacOS.)

You could borrow `clock_gettime` implementation from Macports `legacysupport` – or just build what you need in Macports.

**Comment by minrk** [comment]
conda-forge does have virtual packages for specifying minimum mac versions, so if we ever require a base version _on purpose_, specifying the dependency from https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks would be the way to go.

**Comment by dalcinl** [comment]
@minrk Doesn't this is ultimately an issue for `openmpi-feedstock`?  The `clock_gettime()` function is being used in Open MPI libraries, and not directly in mpi4py.

**Comment by minrk** [comment]
Yes, I don't think this is an mpi4py issue
