### ISSUE TITLE
File not found error when building new packages with mpi4py on conda-forge

### ISSUE THREAD

**Issue by rainwoodman** [conda-forge/mpi4py-feedstock#6]
See https://api.travis-ci.org/jobs/198243501/log.txt?deansi=true

I don't really know what this error means. It worked fine when I grabbed a mac with anaconda (python 3.5 though). 

Does the conda-forge version of mpi4py use mpich or openmpi on macs?

```
ld/mpi4py_test_1486181465719/test_tmp/run_test.py

===== testing package: mpi4py_test-0.0.10-np111py36_0 =====

import: 'mpi4py_test'

Traceback (most recent call last):

  File "/Users/travis/miniconda/conda-bld/mpi4py_test_1486181465719/test_tmp/run_test.py", line 27, in <module>

    import mpi4py_test

  File "/Users/travis/miniconda/conda-bld/mpi4py_test_1486181465719/_t_env/lib/python3.6/site-packages/mpi4py_test/__init__.py", line 1, in <module>

    from mpi4py import MPI

ImportError: dlopen(/Users/travis/miniconda/conda-bld/mpi4py_test_1486181465719/_t_env/lib/python3.6/site-packages/mpi4py/MPI.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libmpi.1.dylib

  Referenced from: /Users/travis/miniconda/conda-bld/mpi4py_test_1486181465719/_t_env/lib/python3.6/site-packages/mpi4py/MPI.cpython-36m-darwin.so

  Reason: image not found

TESTS FAILED: mpi4py_test-0.0.10-np111py36_0
```

**Comment by rainwoodman** [comment]
There are similar errors building on windows: https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.11174/job/peu323jdj81ljbha

**Comment by dalcinl** [comment]
As clearly stated in the recipe, the conda-forge version of mpi4py uses mpich.

Right now there are issues with the mpich & openmpi packages, I'm working on them. Eventually, we will use conda features to provide mpi4py for both mpich and openmpi.

The Windows errors you mention are totally unrelated. We do not have yet a conda-forge version for Microsoft MPI (MS-MPI). The mpi4py package in the default anaconda channel uses MS-MPI, however there is no conda package you can install, you have to so a manual installation of MS-MPI. You can grab code from mpi4py's git repo to install MS-MPI on AppVeyor.

**Comment by rainwoodman** [comment]
Thanks for the explanation. For now I shall disable the windows build and also disable the Python 3.6 then.
