### ISSUE TITLE
How to install mpi4py with Intel MPI?

### ISSUE THREAD

**Issue by YarShev** [conda-forge/mpi4py-feedstock#67]
### Comment:

@dalcinl, hi, I just saw you added Intel MPI build variant to the feedstock. I was wondering if it could be possible to install mpi4py with Intel MPI now from conda-forge?

**Comment by dalcinl** [comment]
> I was wondering if it could be possible to install mpi4py with Intel MPI now from conda-forge?

Making that possible was the whole point of adding the build variant. To install mpi4py with Intel MPI you have to:

```
conda install -c conda-forge impi_rt mpi4py
```

Please note you can also reuse Intel MPI installed externally, and then install the MPICH external variant (and mpi4py and other MPI packages) in your environment. Just check the conda-forge docs for further details.

**Comment by YarShev** [comment]
@dalcinl, when doing `conda install -c conda-forge impi_rt mpi4py` I see the following output.

```bash
Found conflicts! Looking for incompatible packages.
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package mpi conflicts for:
mpi4py -> openmpi[version='>=4.1.6,<5.0a0'] -> mpi==1.0[build='mpich|openmpi']
impi_rt -> mpi==1.0=impi
The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0
  - mpi4py -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.35
```

My system version is the following.

```bash
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by dalcinl** [comment]
Do you get that error when creating an environment from scratch or with an empty environment? Sorry, I cannot test myself on Linux right now.

**Comment by YarShev** [comment]
My steps are the following.

```bash
conda create -n intel-mpi python=3.9
conda activate intel-mpi
conda install -c conda-forge impi_rt mpi4py
# and here error I mentioned above
```

**Comment by dalcinl** [comment]
OK, something seems to be broken, but I have no idea what's going on. 

Maybe @minrk on @leofang can shed some light.

**Comment by oleksandr-pavlyk** [comment]
@dalcinl The issue appears to be that conda packages built for impi variants were not uploaded to the conda channel:

```
$ conda search -c conda-forge mpi4py --subdir=linux-64 --override-channels --info | grep impi | wc
      0       0       0
$ conda search -c conda-forge mpi4py --subdir=win-64 --override-channels --info | grep impi | wc
      0       0       0
```

There are there for mpich and openmpi:

```
$ conda search -c conda-forge mpi4py --subdir=linux-64 --override-channels --info | grep mpich | wc
    204     615    6164
$ conda search -c conda-forge mpi4py --subdir=linux-64 --override-channels --info | grep openmpi | wc
    191     586    6398
```

I can see that `impi` variants were successfully built during the last merged PR: https://github.com/conda-forge/mpi4py-feedstock/pull/65

@conda-forge/core could you help investigate, please?

**Comment by beckermr** [comment]
I see the packages https://anaconda.org/conda-forge/mpi4py/3.1.5/download/linux-64/mpi4py-3.1.5-py310h45b48a2_0.conda but they were marked broken for a reason I cannot quite recall.

**Comment by beckermr** [comment]
yes see these issues:

 - https://github.com/conda-forge/admin-requests/pull/852
 - https://github.com/conda-forge/mpi-feedstock/issues/11

We should bump the build number and rebuild and it will work.

**Comment by beckermr** [comment]
See this one: https://github.com/conda-forge/mpi4py-feedstock/pull/69

**Comment by leofang** [comment]
This should be fixed, if not please kindly open a new issue, thanks!
